### ISSUE TITLE
FirstName_ShouldNotCreate_WhenInvalidInput is failure

### ISSUE THREAD

**Issue by hhko** [dr-marek-jaskula/DomainDrivenDesignUniversity#1] opened 2023-07-19 09:36 UTC
hello.

```cs
public sealed class FirstName : ValueObject
{
    // ...

    public static IList<Error> Validate(string firstName)
    {
        return EmptyList<Error>()
            .If(firstName.IsNullOrEmptyOrWhiteSpace(), FirstNameError.Empty)
            .If(firstName.Length > MaxLength, FirstNameError.TooLong)
            .If(firstName.ContainsIllegalCharacter(), FirstNameError.ContainsIllegalCharacter)
            .If(firstName.ContainsDigit(), FirstNameError.ContainsDigit);
    }
}
```
```cs
public class FirstNameTest : TestBase
{
    private sealed class InvalidFirstNameTestData : TheoryData<string, Error>
    {
        public InvalidFirstNameTestData()
        {
            var invalidCharacter = "_";
            var productNameWithNotAllowedCharacter = $"{TestString(10)}{invalidCharacter}";
            Add(productNameWithNotAllowedCharacter, FirstNameError.ContainsIllegalCharacter);

            var tooLongProductName = TestString(1000);
            Add(tooLongProductName, FirstNameError.TooLong);

            string emptyProductName = string.Empty;
            Add(emptyProductName, FirstNameError.Empty);

            string whitespaceProductName = "    ";
            Add(whitespaceProductName, FirstNameError.Empty);
        }
    }

    [Theory]
    [ClassData(typeof(InvalidFirstNameTestData))]
    public void FirstName_ShouldNotCreate_WhenInvalidInput(string invalidFirstName, Error exceptedError)
    {
        var firstName = FirstName.Create(invalidFirstName);

        firstName.IsFailure.Should().BeTrue();
        firstName.Error.Should().Be(Error.ValidationError);
        firstName.ValidationErrors.Should().HaveCount(1);
        firstName.ValidationErrors.Should().Contain(exceptedError);
    }
}
```
```
UnitTest.ValueObjects.FirstNameTest.FirstName_ShouldNotCreate_WhenInvalidInput(invalidFirstName: "autoLaoeShxyZMPS2GG0Jju3vgm5IIn1etBf6Z9zouFB3QuJbP"..., exceptedError: FirstName.TooLong) 
      Duration: 1 ms
      Message: 
           Expected firstName.ValidationErrors to contain 1 item(s), but found 2: {FirstName.TooLong, FirstName.ContainsDigit}.
```
- invalidFirstName: autoLaoeShxyZMPS`2`GG0Jju3vgm`5`IIn1etBf`6`Z`9`zouFB`3`QuJbP
  - actual result is `FirstName.TooLong`, `FirstName.ContainsDigit`.
  - but expected result is only `FirstName.TooLong`.
  - I think the reason for the failure is that the TestString(`RandomUtilities > GenerateString`) method generates random data containing numbers(Error Code: FirstName.ContainsDigit). https://github.com/dr-marek-jaskula/DomainDrivenDesignUniversity/blob/master/src/Shopway.Domain/Utilities/RandomUtilities.cs#L14
  - how to improve TestString method?

**Comment by dr-marek-jaskula** [comment] 2023-07-20 16:53
Hey hhko,

thanks for your comment :) 

You are right. The problem is the regex that ```GenerageString``` method uses. To be precise this regex pattern:
```
private const string _base64NonAlpaNumbericCharactersPattern = "(?:[/+=]+)";
```

This regex pattern is responsible for excluding the characters that we dont want in our test string. To exclude digits from out test string we need use regex (the fix is in the master right now, with the fest for FirstName as You suggested)
```csharp
private const string _base64NonAlpaNumbericCharactersPattern = "(?:[/+=0-9]+)";
```

Moreover, no matter what character we will exclude from test string, the length will be always correct. 
We can create more regexes and add optional parameters to ```GenerateString``` method, or overload this method with other options.

If You have any questions feel free to ask ;)

**Closed by dr-marek-jaskula** 2023-07-20 16:53 UTC
